/* ==========================================================================
   Qiti admin — English string dictionary
   Flat { 'key.path': 'English text' } map for admin CHROME ONLY — nav
   labels, buttons, toasts, empty states, confirmations, field labels
   that describe what to type. NEVER use this for merchant-authored
   content (product names, campaign copy) — that stays whatever
   language the merchant typed it in.
   ========================================================================== */

export var STRINGS_EN = {
  /* ── عام ── */
  'common.save': 'Save',
  'common.cancel': 'Cancel',
  'common.confirm': 'Confirm',
  'common.delete': 'Delete',
  'common.edit': 'Edit',
  'common.view': 'View',
  'common.back': 'Back',
  'common.add': '+ Add',
  'common.moveUp': 'Move up',
  'common.moveDown': 'Move down',
  'common.choose': 'Choose',
  'common.none': '— None —',
  'common.error': 'Something went wrong.',
  'common.loading': 'Loading…',

  /* ── تنقّل ── */
  'nav.brand': 'Qiti',
  'nav.brandSuffix': 'Admin',
  'nav.toggle': 'Menu',
  'nav.group.content': 'Content',
  'nav.group.store': 'Store',
  'nav.dashboard': 'Dashboard',
  'nav.orders': 'Orders',
  'nav.campaigns': 'Campaigns',
  'nav.products': 'Products',
  'nav.categories': 'Categories',
  'nav.media': 'Media',
  'nav.logout': 'Log out',
  'nav.collapse': 'Collapse sidebar',
  'nav.expand': 'Expand sidebar',

  /* ── دخول ── */
  'login.heading': 'Qiti <em>Dashboard</em>',
  'login.sub': 'Enter your password, then the code sent to your Telegram.',
  'login.password': 'Password',
  'login.code': 'Code (6 digits)',
  'login.next': 'Next',
  'login.signIn': 'Log in',
  'login.sessionExpired': 'Session expired.',

  /* ── حملات ── */
  'campaigns.title': 'Campaigns',
  'campaigns.new': 'New Campaign',
  'campaigns.untitled': 'Untitled',
  'campaigns.published': 'Published',
  'campaigns.draft': 'Draft',
  'campaigns.duplicate': 'Duplicate',
  'campaigns.publish': 'Publish',
  'campaigns.unpublish': 'Unpublish',
  'campaigns.emptyTitle': 'No campaigns yet',
  'campaigns.emptyBody': 'Create your first campaign to launch your first product page.',
  'campaigns.basics': 'Basics',
  'campaigns.name': 'Campaign name',
  'campaigns.nameHint': 'Internal only — customers never see this',
  'campaigns.slug': 'Slug',
  'campaigns.slugHint': 'qitishop.netlify.app/<slug>',
  'campaigns.selectProduct': '— Select a product —',
  'campaigns.product': 'Product',
  'campaigns.seoTitle': 'Google title',
  'campaigns.seoDescription': 'Google description',
  'campaigns.sections': 'Sections',
  'campaigns.sectionsEmptyTitle': 'No sections yet',
  'campaigns.sectionsEmptyBody': 'Select a product and click "Load starter sections".',
  'campaigns.addSection': 'Add section',
  'campaigns.blankSections': 'Load starter sections',
  'campaigns.enabled': 'Enabled',
  'campaigns.viewportMobile': 'Mobile',
  'campaigns.viewportTablet': 'Tablet',
  'campaigns.viewportDesktop': 'Desktop',
  'campaigns.previewTitle': 'Preview',
  'campaigns.viewPage': 'View page',
  'campaigns.saveKeepPublished': 'Save (stays published)',
  'campaigns.savePublish': 'Save & publish',
  'campaigns.saved': 'Saved.',
  'campaigns.publishedToast': 'Published at /{slug}',
  'campaigns.deleted': 'Deleted.',
  'campaigns.deleteConfirmTitle': 'Delete this campaign?',
  'campaigns.deleteConfirmBody': 'The link will 404 for anyone who visits it.',

  /* ── الشكل (ثيم الحملة) ── */
  'theme.title': 'Appearance',
  'theme.mode': 'Mode',
  'theme.font': 'Font',
  'theme.radius': 'Corner radius',
  'theme.accent': 'Brand color',
  'theme.accentText': 'Text on brand color',
  'theme.bg': 'Background',
  'theme.surface': 'Card background',
  'theme.text': 'Text color',
  'theme.contrastWarn': "⚠️ Contrast between text and background is {ratio}:1 — below 4.5:1. The page won't be legible, and the server will reject this theme.",
  'theme.contrastOk': 'Contrast {ratio}:1 — good.',

  /* ── منتجات ── */
  'products.title': 'Products',
  'products.new': 'New Product',
  'products.emptyTitle': 'No products yet',
  'products.emptyBody': 'Create your first product to start building campaigns around it.',
  'products.groupBasics': 'Basics',
  'products.name': 'Product name',
  'products.slug': 'Slug',
  'products.slugHint': 'qitishop.netlify.app/p/<slug>',
  'products.shortDescription': 'Short description',
  'products.shortDescriptionHint': 'Max 300 characters — used in listings and previews',
  'products.description': 'Full description',
  'products.descriptionHint': 'Max 5000 characters',
  'products.groupMedia': 'Images',
  'products.media': 'Gallery',
  'products.mediaSrc': 'Image',
  'products.mediaAlt': 'Description',
  'products.mediaAltHint': 'For screen readers, and for Google',
  'products.mediaHint': 'First image is the primary one — drag with ↑/↓ to reorder',
  'products.groupPricing': 'Pricing',
  'products.type': 'Type',
  'products.category': 'Category',
  'products.noCategory': '— No category —',
  'products.price': 'Price (DZD)',
  'products.compareAtPrice': 'Compare-at price (DZD)',
  'products.compareAtPriceHint': 'Shown struck through on the page',
  'products.unitCost': 'Unit cost (DZD)',
  'products.unitCostHint': 'Used to calculate profit',
  'products.profitMargin': 'Profit margin',
  'products.profitMarginHint': 'Computed from price and unit cost — not stored',
  'products.groupInventory': 'Inventory',
  'products.defaultStockThreshold': 'Default low-stock threshold',
  'products.defaultStockThresholdHint': 'Used to seed new variants only — edit live thresholds from the stock table below',
  'products.initialStock': 'Initial stock quantity',
  'products.initialStockHint': 'Only applies to products with no options (a single variant). Products with options start at 0 — fill the stock table after saving.',
  'products.groupOrganize': 'Organize',
  'products.status': 'Status',
  'products.tags': 'Tags',
  'products.tagsHint': 'One per line',
  'products.featured': 'Featured',
  'products.groupShipping': 'Shipping',
  'products.weightGrams': 'Weight (grams)',
  'products.weightGramsHint': 'Leave empty if unknown',
  'products.shippingNote': 'Shipping note',
  'products.shippingNoteHint': 'e.g. Fragile, ships in 2 boxes',
  'products.groupSeo': 'SEO',
  'products.seoTitle': 'Google title',
  'products.seoTitleHint': 'Leave empty to use the product name',
  'products.seoDescription': 'Google description',
  'products.seoDescriptionHint': 'Leave empty to use the short description',
  'products.seoOgImage': 'Social share image',
  'products.seoOgImageHint': 'Shown when the link is shared — leave empty to use the primary image',
  'products.optionsTitle': 'Options (sizes, colors…)',
  'products.optionsHint': '⚠️ Values map to stock by position, not name. Removing or reordering a value shifts stock onto the wrong size/color — recheck the Stock table after saving.',
  'products.optionName': 'Option name',
  'products.optionNameHint': 'e.g. Size',
  'products.optionValues': 'Values',
  'products.optionValuesHint': 'One per line: S / M / L',
  'products.addOption': '+ Add option',
  'products.saved': 'Saved.',

  /* ── فاريانتات ── */
  'variants.title': 'Variants',
  'variants.merchantSku': 'Merchant SKU',
  'variants.barcode': 'Barcode',
  'variants.priceDelta': 'Price difference (DZD)',

  /* ── مخزون ── */
  'stock.title': 'Stock',
  'stock.variant': 'Variant',
  'stock.quantity': 'Quantity',
  'stock.threshold': 'Alert threshold',
  'stock.single': 'Single',
  'stock.updated': 'Stock updated.',

  /* ── فئات ── */
  'categories.title': 'Categories',
  'categories.new': 'New Category',
  'categories.emptyTitle': 'No categories yet',
  'categories.emptyBody': 'Create your first category to organize products.',
  'categories.editTitle': 'Edit category',
  'categories.newTitle': 'New category',
  'categories.name': 'Name',
  'categories.slug': 'Slug',
  'categories.tagline': 'Short tagline',
  'categories.icon': 'Icon',
  'categories.sort': 'Sort order',
  'categories.saved': 'Saved.',

  /* ── ميديا ── */
  'media.title': 'Media',
  'media.uploadHint': 'jpeg / png / webp / avif — 5 MB max',
  'media.uploadAction': 'Upload an image',
  'media.emptyTitle': 'No media yet',
  'media.emptyBody': 'Upload an image to use it in campaigns and products.',
  'media.uploading': 'Uploading…',
  'media.uploaded': 'Uploaded.',
  'media.pickTitle': 'Choose image',
  'media.pickEmpty': 'No media yet. Upload one.',
  'media.deleteConfirmTitle': 'Delete this media file?',
  'media.deleteConfirmBody': 'Campaigns using it will lose the image.',

  /* ── طلبات ── */
  'orders.title': 'Orders',
  'orders.readonlyHint': 'Orders are accepted, denied, and marked delivered from Telegram — this list is read-only.',
  'orders.emptyTitle': 'No orders yet',
  'orders.emptyBody': 'Orders placed by customers will show up here.',
  'orders.emptyFilteredTitle': 'No matching orders',
  'orders.emptyFilteredBody': 'Try a different search or status filter.',
  'orders.searchPlaceholder': 'Search name or phone…',
  'orders.filterAll': 'All statuses',
  'orders.statusPending': 'Pending',
  'orders.statusAccepted': 'Accepted',
  'orders.statusDenied': 'Denied',
  'orders.statusDelivered': 'Delivered',
  'orders.statusReturned': 'Returned',
  'orders.detailTitle': 'Order details',
  'orders.customer': 'Customer',
  'orders.phone': 'Phone',
  'orders.location': 'Location',
  'orders.shipping': 'Shipping',
  'orders.shippingHome': 'Home delivery',
  'orders.shippingDesk': 'Desk pickup',
  'orders.quantity': 'Quantity',
  'orders.unitPrice': 'Unit price',
  'orders.total': 'Total',
  'orders.product': 'Product',
  'orders.channel': 'Channel',
  'orders.placedAt': 'Placed',
  'orders.decision': 'Decision',
  'orders.decidedBy': '{who} · {when}',
  'orders.deniedReason': 'Reason',
  'orders.confirmedByPhone': 'Phone-confirmed by {who} · {when}',
  'orders.delivery': 'Delivery outcome',
  'orders.returnReceivedAt': 'Return received',
  'orders.customerHistory': 'Customer history',
  'orders.historyDelivered': '{n} delivered',
  'orders.historyDenied': '{n} denied',
  'orders.historyReturned': '{n} returned',
  'orders.historyNone': 'First order from this customer',
  'orders.blockedFlag': 'This number is on your manual block list',

  /* ── لوحة القيادة ── */
  'dashboard.title': 'Dashboard',
  'dashboard.range7': 'Last 7 days',
  'dashboard.range30': 'Last 30 days',
  'dashboard.range90': 'Last 90 days',
  'dashboard.revenue': 'Revenue',
  'dashboard.revenueHint': 'Delivered orders only',
  'dashboard.orders': 'Orders',
  'dashboard.conversion': 'Conversion',
  'dashboard.conversionHint': 'Orders placed ÷ unique visits',
  'dashboard.aov': 'Avg. order value',
  'dashboard.productsSold': 'Products sold',
  'dashboard.visits': 'Visits',
  'dashboard.views': 'Views',
  'dashboard.customers': 'Customers',
  'dashboard.trackingSince': 'Since {date}',
  'dashboard.noVisitData': 'No visit data yet',
  'dashboard.revenueChart': 'Revenue',
  'dashboard.pipeline': 'In transit',
  'dashboard.ordersChart': 'Orders placed',
  'dashboard.byCategory': 'Sales by category',
  'dashboard.topProducts': 'Top products',
  'dashboard.units': '{n} sold',
  'dashboard.activeCampaigns': 'Active campaigns',
  'dashboard.lowStock': 'Low stock',
  'dashboard.recentOrders': 'Recent orders',
  'dashboard.legacyProduct': 'Legacy landing page',
  'dashboard.uncategorized': 'Uncategorized',
  'dashboard.legacyStock': 'Legacy stock counter',
  'dashboard.emptyTitle': 'No activity yet',
  'dashboard.emptyBody': 'Orders and visits will show up here once your store starts getting traffic.',
  'dashboard.noDataTitle': 'Nothing here yet',
  'dashboard.viewAll': 'View all',

  /* ── حالات فارغة/خطأ ── */
  'state.errorTitle': 'Something went wrong',
  'state.retry': 'Try again',
};
