/* ==========================================================================
   Qiti admin — نصوص الحملات
   يشمل theme.* (شكل الحملة): هو جزء من محرّر الحملة، ماشي إعداد عام
   للوحة — فبلاصتو هنا مع باقي المحرّر.
   ========================================================================== */

export var CAMPAIGNS_EN = {
  'campaigns.title': 'Campaigns',
  'campaigns.new': 'New Campaign',
  'campaigns.untitled': 'Untitled',
  'campaigns.published': 'Published',
  'campaigns.draft': 'Draft',
  'campaigns.duplicate': 'Duplicate',
  'campaigns.publish': 'Publish',
  'campaigns.unpublish': 'Unpublish',
  'campaigns.emptyTitle': 'No campaigns yet',
  'campaigns.emptyBody': 'Create your first campaign to launch your first product page.',
  'campaigns.basics': 'Basics',
  'campaigns.name': 'Campaign name',
  'campaigns.nameHint': 'Internal only — customers never see this',
  'campaigns.slug': 'Slug',
  'campaigns.slugHint': 'qitishop.netlify.app/<slug>',
  'campaigns.selectProduct': '— Select a product —',
  'campaigns.product': 'Product',
  'campaigns.seoTitle': 'Google title',
  'campaigns.seoDescription': 'Google description',
  'campaigns.sections': 'Sections',
  'campaigns.sectionsEmptyTitle': 'No sections yet',
  'campaigns.sectionsEmptyBody': 'Select a product and click "Load starter sections".',
  'campaigns.addSection': 'Add section',
  'campaigns.allSectionsUsed': 'Every section type is already on this page.',
  'campaigns.blankSections': 'Load starter sections',
  'campaigns.enabled': 'Enabled',
  'campaigns.viewportMobile': 'Mobile',
  'campaigns.viewportTablet': 'Tablet',
  'campaigns.viewportDesktop': 'Desktop',
  'campaigns.previewTitle': 'Preview',
  'campaigns.viewPage': 'View page',
  'campaigns.saveKeepPublished': 'Save (stays published)',
  'campaigns.savePublish': 'Save & publish',
  'campaigns.saved': 'Saved.',
  'campaigns.publishedToast': 'Published at /{slug}',
  'campaigns.deleted': 'Deleted.',
  'campaigns.deleteConfirmTitle': 'Delete this campaign?',
  'campaigns.deleteConfirmBody': 'The link will 404 for anyone who visits it.',

  /* ── قائمة الحملات: بحث/فلتر/جدول ── */
  'campaigns.searchPlaceholder': 'Search by name or slug…',
  'campaigns.filterAll': 'All statuses',
  'campaigns.filterAriaLabel': 'Filter by status',
  'campaigns.emptyFilteredTitle': 'No campaigns match',
  'campaigns.emptyFilteredBody': 'Try a different search or filter.',
  'campaigns.colName': 'Campaign',
  'campaigns.colStatus': 'Status',
  'campaigns.colUpdated': 'Updated',
  'campaigns.rowMenuLabel': 'More actions for {name}',

  /* ── محرّر الحملة: الخطوات ── */
  'campaigns.stepDetails': 'Details',
  'campaigns.stepDesign': 'Design',
  'campaigns.stepContent': 'Content',
  'campaigns.stepReview': 'Review & publish',
  'campaigns.stepBack': 'Back',
  'campaigns.stepNext': 'Next',
  'campaigns.stepPosition': 'Step {n} of {total}',
  'campaigns.productRequired': 'Pick a product before publishing.',
  'campaigns.addSectionLabel': 'Section type to add',

  /* ── خطوة المراجعة ── */
  'campaigns.reviewTitle': 'Ready to publish?',
  'campaigns.reviewPublishHint': 'Use "Save & publish" above to make this page live.',
  'campaigns.reviewSummaryTitle': 'Summary',
  'campaigns.reviewLink': 'Link',
  'campaigns.reviewSections': 'Sections',
  'campaigns.reviewSectionsCount': '{enabled} of {total} enabled',
  'campaigns.reviewStatus': 'Status',

  /* ── الشكل (ثيم الحملة) ── */
  'theme.title': 'Appearance',
  'theme.mode': 'Mode',
  'theme.font': 'Font',
  'theme.radius': 'Corner radius',
  'theme.accent': 'Brand color',
  'theme.accentText': 'Text on brand color',
  'theme.bg': 'Background',
  'theme.surface': 'Card background',
  'theme.text': 'Text color',
  'theme.contrastWarn': "⚠️ Contrast between text and background is {ratio}:1 — below 4.5:1. Customers will struggle to read the page.",
  'theme.contrastOk': 'Contrast {ratio}:1 — good.',
};
