
export var DASHBOARD_EN = {
  'dashboard.title': 'Dashboard',
  'dashboard.range7': 'Last 7 days',
  'dashboard.range30': 'Last 30 days',
  'dashboard.range90': 'Last 90 days',
  'dashboard.revenue': 'Revenue',
  'dashboard.revenueHint': 'Delivered orders only',
  'dashboard.profit': 'Net profit',
  'dashboard.profitHint': 'After cost, ads and returns',
  'dashboard.revenueWaiting': '{n} order(s) in transit — revenue counts only once you mark 📦 Delivered in Telegram',
  'dashboard.orders': 'Orders',
  'dashboard.ordersSub': '{delivered} delivered · {pending} pending',
  'dashboard.campaignStats': '{visits} visits · {orders} orders · {conv}',
  'dashboard.rangeAriaLabel': 'Date range',
  'dashboard.conversion': 'Conversion',
  'dashboard.aov': 'Avg. order value',
  'dashboard.productsSold': 'Products sold',
  'dashboard.visits': 'Visits',
  'dashboard.customers': 'Customers',
  'dashboard.trackingSince': 'Since {date}',
  'dashboard.noVisitData': 'No visit data yet',
  'dashboard.revenueChart': 'Revenue',
  'dashboard.pipeline': 'In transit',
  'dashboard.ordersChart': 'Orders placed',
  'dashboard.byCategory': 'Sales by category',
  'dashboard.topProducts': 'Top products',
  'dashboard.units': '{n} sold',
  'dashboard.activeCampaigns': 'Active campaigns',
  'dashboard.offersTitle': 'Bundles & upsells',
  'dashboard.bundleOrders': 'Bundle orders',
  'dashboard.bundleUnits': '{units} bundles sold',
  'dashboard.upsellConversion': 'Upsell conversion',
  'dashboard.upsellAccepted': '{accepted} accepted of {offers} offered',
  'dashboard.upsellRevenue': 'Upsell revenue',
  'dashboard.upsellPerOrder': '{amount} per delivered order',
  'dashboard.lowStock': 'Low stock',
  'dashboard.recentOrders': 'Recent orders',
  'dashboard.legacyProduct': 'Legacy landing page',
  'dashboard.uncategorized': 'Uncategorized',
  'dashboard.legacyStock': 'Legacy stock counter',
  'dashboard.emptyTitle': 'No activity yet',
  'dashboard.emptyBody': 'Orders and visits will show up here once your store starts getting traffic.',
  'dashboard.noDataTitle': 'Nothing here yet',
  'dashboard.viewAll': 'View all',
};
