
export var NAV_EN = {
  'nav.brand': 'Qiti',
  'nav.brandSuffix': 'Admin',
  'nav.toggle': 'Menu',
  'nav.group.content': 'Content',
  'nav.group.store': 'Store',
  'nav.dashboard': 'Dashboard',
  'nav.queue': 'Call queue',
  'nav.orders': 'Orders',
  'nav.campaigns': 'Campaigns',
  'nav.products': 'Products',
  'nav.categories': 'Categories',
  'nav.media': 'Media',
  'nav.logout': 'Log out',
  'nav.collapse': 'Collapse sidebar',
  'nav.expand': 'Expand sidebar',
  'nav.themeToggle': 'Toggle dark mode',
  'nav.themeDark': 'Dark mode',
  'nav.themeLight': 'Light mode',
};
