/* ==========================================================================
   Qiti admin — نصوص الطلبات
   ⚠️ اللوحة تعرض برك. القبول/الرفض/التوصيل يبقاو من تيليغرام — أي نص
   جديد هنا لازمو يبقى في لغة "شوف"، ماشي "قرّر".
   ========================================================================== */

export var ORDERS_EN = {
  'orders.title': 'Orders',
  'orders.readonlyHint': 'Orders are accepted, denied, and marked delivered from Telegram — this list is read-only.',
  'orders.emptyTitle': 'No orders yet',
  'orders.emptyBody': 'Orders placed by customers will show up here.',
  'orders.emptyFilteredTitle': 'No matching orders',
  'orders.emptyFilteredBody': 'Try a different search or status filter.',
  'orders.searchPlaceholder': 'Search name or phone…',
  'orders.filterAriaLabel': 'Filter by status',
  'orders.colDate': 'Date',
  'orders.colStatus': 'Status',
  'orders.paginationSummary': '{from}–{to} of {n}',
  'orders.pagePrev': 'Previous',
  'orders.pageNext': 'Next',
  'orders.filterAll': 'All statuses',
  'orders.statusPending': 'Pending',
  'orders.statusAccepted': 'Accepted',
  'orders.statusDenied': 'Denied',
  'orders.statusDelivered': 'Delivered',
  'orders.statusReturned': 'Returned',
  'orders.detailTitle': 'Order details',
  'orders.customer': 'Customer',
  'orders.phone': 'Phone',
  'orders.location': 'Location',
  'orders.shipping': 'Shipping',
  'orders.shippingHome': 'Home delivery',
  'orders.shippingDesk': 'Desk pickup',
  'orders.quantity': 'Quantity',
  'orders.unitPrice': 'Unit price',
  'orders.total': 'Total',
  'orders.product': 'Product',
  'orders.channel': 'Channel',
  'orders.placedAt': 'Placed',
  'orders.decision': 'Decision',
  'orders.decidedBy': '{who} · {when}',
  'orders.deniedReason': 'Reason',
  'orders.confirmedByPhone': 'Phone-confirmed by {who} · {when}',
  'orders.delivery': 'Delivery outcome',
  'orders.returnReceivedAt': 'Return received',
  'orders.customerHistory': 'Customer history',
  'orders.historyDelivered': '{n} delivered',
  'orders.historyDenied': '{n} denied',
  'orders.historyReturned': '{n} returned',
  'orders.historyNone': 'First order from this customer',
  'orders.blockedFlag': 'This number is on your manual block list',
};
