export var QUEUE_EN = {
  'queue.title': 'Call queue',
  'queue.hint': 'Everything waiting on a call or a decision, oldest first. Every attempt is recorded here and on the Telegram message, so "no answer, third try" is something the shop knows.',

  'queue.countConfirmed': 'Confirmed',
  'queue.countDue': 'To call',
  'queue.countStalled': 'Out of tries',
  'queue.countWaiting': 'Scheduled',

  'queue.filterAriaLabel': 'Filter the queue',
  'queue.filterAll': 'Whole queue',
  'queue.filterConfirmed': 'Confirmed',
  'queue.filterDue': 'To call',
  'queue.filterStalled': 'Out of tries',
  'queue.filterWaiting': 'Scheduled',
  'queue.refresh': 'Refresh',

  'queue.stateConfirmed': 'Confirmed by phone',
  'queue.stateDue': 'Needs a call',
  'queue.stateStalled': 'Out of tries',
  'queue.stateWaiting': 'Scheduled',
  'queue.leadTag': 'Unfinished order',

  'queue.neverCalled': 'Never called',
  'queue.attempts': 'Try {n} · {outcome} · {when}',
  'queue.nextCall': 'Next try {when}',
  'queue.waitingHint': 'Overdue orders come back to the top on their own.',
  'queue.stalledHint': 'Called {n} times with no result — this one needs a decision, not another call.',

  'queue.outcomeReached': 'Answered — confirmed',
  'queue.outcomeNoAnswer': 'No answer',
  'queue.outcomeBusy': 'Busy',
  'queue.outcomeOff': 'Phone off',
  'queue.outcomeCallback': 'Asked me to call back',
  'queue.outcomeWrong': 'Wrong number',

  'queue.call': 'Call',
  'queue.whatsapp': 'WhatsApp',
  'queue.logNoAnswer': 'No answer',
  'queue.logReached': 'Answered',
  'queue.logMore': 'Other outcome…',
  'queue.accept': 'Accept',
  'queue.deny': 'Deny',
  'queue.dismiss': 'Drop from queue',

  'queue.logTitle': 'Log the call',
  'queue.logOutcome': 'What happened?',
  'queue.logNote': 'Note (optional)',
  'queue.logNotePlaceholder': 'e.g. asked for the blue one instead',
  'queue.logCallbackAt': 'Call back at',
  'queue.logCallbackHint': 'Leave empty and the next try is scheduled from the outcome.',
  'queue.logSave': 'Save the attempt',

  'queue.denyTitle': 'Deny this order',
  'queue.denyReason': 'Why?',
  'queue.denyPlaceholder': 'e.g. never answered after 5 tries',
  'queue.denyHint': 'The reason shows up in the Telegram message and in the reports — "no answer" and "too expensive" are not the same problem.',
  'queue.denyConfirm': 'Deny the order',

  'queue.loggedCall': 'Attempt {n} saved',
  'queue.accepted': 'Order accepted — stock updated',
  'queue.denied': 'Order denied',
  'queue.dismissed': 'Dropped from the queue',

  'queue.emptyTitle': 'Nothing waiting',
  'queue.emptyBody': 'No order needs a call or a decision right now. New ones land here the second they come in.',
  'queue.emptyFilteredTitle': 'Nothing in this filter',
  'queue.emptyFilteredBody': 'Other rows are still in the queue — switch the filter to see them.',
};
